name: CICD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: validate branch name
      uses: ./.github/actions/validate-branch-name
      with:
        branch_name: ${{ github.head_ref }}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test /p:Configuration=Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

  mutation-tests:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      strategy:
        fail-fast: true
      steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: validate branch name
        uses: ./.github/actions/validate-branch-name
        with:
          branch_name: ${{ github.head_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: mutation tests
        run: |
          dotnet tool restore
          dotnet stryker -b 70

      - name: upload test mutation reports
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: mutation-report
          path: "**/mutation-report.html"
          retention-days: 30
